import { FormEvent, useEffect, useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import { api } from '../api';
import type { Assignment, Client, Profile, ProxyRecord } from '../types';
import { Badge, Card, Empty, ErrorBanner, Field, Modal, PageHead } from '../components/ui';

export function AssignmentsView() {
  const [items, setItems] = useState<Assignment[]>([]); const [clients, setClients] = useState<Client[]>([]); const [profiles, setProfiles] = useState<Profile[]>([]); const [proxies, setProxies] = useState<ProxyRecord[]>([]); const [open, setOpen] = useState(false); const [error, setError] = useState<string | null>(null);
  async function load() { try { const [a,c,p,x] = await Promise.all([api.assignments.list(), api.clients.list(), api.profiles.list(), api.proxies.list()]); setItems(a); setClients(c); setProfiles(p); setProxies(x); } catch (e: any) { setError(e.message); } } useEffect(() => { void load(); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const fd = new FormData(event.currentTarget); try { await api.assignments.create({ clientId: String(fd.get('clientId')), profileId: String(fd.get('profileId')), proxyId: String(fd.get('proxyId') || '') || null, enabled: true }); setOpen(false); await load(); } catch (e: any) { setError(e.message); } }
  async function remove(item: Assignment) { if (!confirm('¿Quitar esta asignación?')) return; try { await api.assignments.remove(item.id); await load(); } catch (e: any) { setError(e.message); } }
  const canCreate = clients.length > 0 && profiles.length > 0;
  return <><PageHead title="Asignaciones" description="Relaciona Cliente → Perfil/Web → Proxy. El Client solo ve perfiles que tengan una asignación activa y una suscripción vigente." actions={<button className="button primary" onClick={() => setOpen(true)} disabled={!canCreate}><Plus size={14} />Nueva asignación</button>} /><ErrorBanner message={error} /><Card>{items.length === 0 ? <Empty title="No hay asignaciones" description="Crea un cliente y un perfil para empezar a entregar accesos." /> : <div className="table-wrap"><table><thead><tr><th>Cliente</th><th>Perfil</th><th>Proxy</th><th>Estado</th><th /></tr></thead><tbody>{items.map((a) => <tr key={a.id}><td><div className="table-primary">{a.client?.name || a.client_id}</div><div className="table-secondary">{a.client?.email}</div></td><td><div className="table-primary">{a.profile?.name || a.profile_id}</div><div className="table-secondary">{a.profile?.url}</div></td><td>{a.proxy ? <><div className="table-primary">{a.proxy.name}</div><div className="table-secondary mono">{a.proxy.host}:{a.proxy.port}</div></> : <Badge>Directo</Badge>}</td><td><Badge tone={a.enabled ? 'ok' : 'bad'}>{a.enabled ? 'Activa' : 'Inactiva'}</Badge></td><td><button className="button danger small" onClick={() => remove(a)}><Trash2 size={12} />Quitar</button></td></tr>)}</tbody></table></div>}</Card>{open && <Modal title="Nueva asignación" onClose={() => setOpen(false)} actions={<><button className="button secondary" onClick={() => setOpen(false)}>Cancelar</button><button className="button primary" form="assignment-form" type="submit">Asignar</button></>}><form id="assignment-form" className="form-grid" onSubmit={submit}><Field label="Cliente" className="span-2"><select className="select" name="clientId" required>{clients.map((c) => <option value={c.id} key={c.id}>{c.name} · {c.email}</option>)}</select></Field><Field label="Perfil / Web" className="span-2"><select className="select" name="profileId" required>{profiles.map((p) => <option value={p.id} key={p.id}>{p.name}</option>)}</select></Field><Field label="Proxy" className="span-2"><select className="select" name="proxyId"><option value="">Conexión directa</option>{proxies.filter((p) => p.enabled).map((p) => <option value={p.id} key={p.id}>{p.name} · {p.host}:{p.port}</option>)}</select></Field></form></Modal>}</>;
}
