import { FormEvent, useEffect, useMemo, useState } from 'react';
import { CalendarClock, KeyRound, Plus, Trash2 } from 'lucide-react';
import { api } from '../api';
import type { Client, Plan } from '../types';
import { Badge, Card, Empty, ErrorBanner, Field, Modal, PageHead } from '../components/ui';

function dateInput(value: Date) { return value.toISOString().slice(0, 10); }

export function ClientsView() {
  const [clients, setClients] = useState<Client[]>([]);
  const [plans, setPlans] = useState<Plan[]>([]);
  const [createOpen, setCreateOpen] = useState(false);
  const [credentialsClient, setCredentialsClient] = useState<Client | null>(null);
  const [subscriptionClient, setSubscriptionClient] = useState<Client | null>(null);
  const [error, setError] = useState<string | null>(null);
  const defaultStart = useMemo(() => dateInput(new Date()), []);

  async function load() { try { const [clientRows, planRows] = await Promise.all([api.clients.list(), api.plans.list()]); setClients(clientRows); setPlans(planRows); } catch (e: any) { setError(e.message); } }
  useEffect(() => { void load(); }, []);

  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const fd = new FormData(event.currentTarget); try { await api.clients.create({ name: String(fd.get('name') || '').trim(), email: String(fd.get('email') || '').trim(), phone: String(fd.get('phone') || '').trim(), planId: String(fd.get('planId') || ''), startsAt: new Date(String(fd.get('startsAt')) + 'T00:00:00Z').toISOString(), expiresAt: new Date(String(fd.get('expiresAt')) + 'T23:59:59Z').toISOString(), username: String(fd.get('username') || '').trim(), password: String(fd.get('password') || '') }); setCreateOpen(false); await load(); } catch (e: any) { setError(e.message); } }
  async function resetCredentials(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!credentialsClient) return; const fd = new FormData(event.currentTarget); try { await api.clients.credentials(credentialsClient.id, String(fd.get('username') || '').trim(), String(fd.get('password') || '')); setCredentialsClient(null); await load(); } catch (e: any) { setError(e.message); } }
  async function renew(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!subscriptionClient) return; const fd = new FormData(event.currentTarget); try { await api.clients.subscription(subscriptionClient.id, { planId: String(fd.get('planId')), startsAt: new Date(String(fd.get('startsAt')) + 'T00:00:00Z').toISOString(), expiresAt: new Date(String(fd.get('expiresAt')) + 'T23:59:59Z').toISOString(), status: 'active' }); setSubscriptionClient(null); await load(); } catch (e: any) { setError(e.message); } }
  async function toggle(client: Client) { try { await api.clients.update(client.id, { status: client.status === 'active' ? 'suspended' : 'active' }); await load(); } catch (e: any) { setError(e.message); } }
  async function remove(client: Client) { if (!confirm(`¿Eliminar definitivamente a ${client.name}?`)) return; try { await api.clients.remove(client.id); await load(); } catch (e: any) { setError(e.message); } }

  return <><PageHead title="Clientes" description="Clientes reales con credenciales de PC hasheadas, plan vigente y control de suspensión desde el servidor." actions={<button className="button primary" onClick={() => setCreateOpen(true)} disabled={plans.length === 0}><Plus size={14} />Nuevo cliente</button>} /><ErrorBanner message={error} />{plans.length === 0 && <div className="error-banner">Primero crea al menos un plan. Un cliente sin suscripción no puede autenticarse en userFLEX Client.</div>}<Card>{clients.length === 0 ? <Empty title="No hay clientes" description="Crea el primer cliente cuando tengas un plan definido." /> : <div className="table-wrap"><table><thead><tr><th>Cliente</th><th>Login PC</th><th>Plan / vencimiento</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{clients.map((c) => { const expired = c.subscription ? new Date(c.subscription.expires_at).getTime() <= Date.now() : true; return <tr key={c.id}><td><div className="table-primary">{c.name}</div><div className="table-secondary">{c.email}{c.phone ? ` · ${c.phone}` : ''}</div></td><td><div className="table-primary mono">{c.credential?.username || 'Sin credenciales'}</div><div className="table-secondary">{c.credential?.has_password ? 'Contraseña configurada' : 'Sin contraseña'}</div></td><td>{c.subscription ? <><div className="table-primary">{c.subscription.plan?.name || 'Plan'}</div><div className="table-secondary">vence {new Date(c.subscription.expires_at).toLocaleDateString()}</div></> : <Badge tone="bad">Sin plan</Badge>}</td><td><Badge tone={c.status === 'active' && !expired ? 'ok' : 'bad'}>{c.status === 'suspended' ? 'Suspendido' : expired ? 'Vencido' : 'Activo'}</Badge></td><td><div className="toolbar" style={{ margin: 0 }}><button className="button secondary small" onClick={() => setCredentialsClient(c)}><KeyRound size={12} />Credenciales</button><button className="button secondary small" onClick={() => setSubscriptionClient(c)}><CalendarClock size={12} />Plan</button><button className="button secondary small" onClick={() => toggle(c)}>{c.status === 'active' ? 'Suspender' : 'Activar'}</button><button className="button danger small" onClick={() => remove(c)}><Trash2 size={12} /></button></div></td></tr>; })}</tbody></table></div>}</Card>
  {createOpen && <Modal title="Nuevo cliente" onClose={() => setCreateOpen(false)} actions={<><button className="button secondary" onClick={() => setCreateOpen(false)}>Cancelar</button><button className="button primary" form="client-form" type="submit">Crear cliente</button></>}><form id="client-form" onSubmit={create} className="form-grid"><Field label="Nombre"><input className="input" name="name" required maxLength={120} /></Field><Field label="Correo"><input className="input" name="email" type="email" required /></Field><Field label="Teléfono"><input className="input" name="phone" maxLength={40} /></Field><Field label="Plan"><select className="select" name="planId" required>{plans.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Inicio"><input className="input" name="startsAt" type="date" defaultValue={defaultStart} required /></Field><Field label="Vencimiento"><input className="input" name="expiresAt" type="date" defaultValue={dateInput(new Date(Date.now() + 30 * 86400000))} required /></Field><Field label="Usuario para PC"><input className="input" name="username" required minLength={3} maxLength={80} autoComplete="off" /></Field><Field label="Contraseña para PC" help="Mínimo 10 caracteres; nunca se vuelve a mostrar."><input className="input" name="password" type="password" required minLength={10} autoComplete="new-password" /></Field></form></Modal>}
  {credentialsClient && <Modal title={`Cambiar credenciales · ${credentialsClient.name}`} onClose={() => setCredentialsClient(null)} actions={<><button className="button secondary" onClick={() => setCredentialsClient(null)}>Cancelar</button><button className="button primary" form="credentials-form" type="submit">Guardar</button></>}><form id="credentials-form" onSubmit={resetCredentials} className="form-grid"><Field label="Usuario" className="span-2"><input className="input" name="username" defaultValue={credentialsClient.credential?.username || ''} required minLength={3} autoComplete="off" /></Field><Field label="Nueva contraseña" className="span-2" help="El servidor reemplaza el hash anterior; no almacena texto plano."><input className="input" name="password" type="password" required minLength={10} autoComplete="new-password" /></Field></form></Modal>}
  {subscriptionClient && <Modal title={`Renovar plan · ${subscriptionClient.name}`} onClose={() => setSubscriptionClient(null)} actions={<><button className="button secondary" onClick={() => setSubscriptionClient(null)}>Cancelar</button><button className="button primary" form="subscription-form" type="submit">Guardar</button></>}><form id="subscription-form" onSubmit={renew} className="form-grid"><Field label="Plan" className="span-2"><select className="select" name="planId" defaultValue={subscriptionClient.subscription?.plan_id || plans[0]?.id}>{plans.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Inicio"><input className="input" name="startsAt" type="date" defaultValue={defaultStart} required /></Field><Field label="Vencimiento"><input className="input" name="expiresAt" type="date" defaultValue={dateInput(new Date(Date.now() + 30 * 86400000))} required /></Field></form></Modal>}</>;
}
