import { FormEvent, useEffect, useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import { api } from '../api';
import type { Plan } from '../types';
import { Badge, Card, Empty, ErrorBanner, Field, Modal, PageHead } from '../components/ui';

export function PlansView() {
  const [plans, setPlans] = useState<Plan[]>([]); const [open, setOpen] = useState(false); const [error, setError] = useState<string | null>(null);
  async function load() { try { setPlans(await api.plans.list()); } catch (e: any) { setError(e.message); } } useEffect(() => { void load(); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const fd = new FormData(event.currentTarget); try { await api.plans.create({ name: String(fd.get('name') || '').trim(), duration_days: Number(fd.get('durationDays') || 30), max_devices: Number(fd.get('maxDevices') || 1), max_profiles: Number(fd.get('maxProfiles') || 1), enabled: true }); setOpen(false); await load(); } catch (e: any) { setError(e.message); } }
  async function remove(plan: Plan) { if (!confirm(`¿Eliminar el plan ${plan.name}?`)) return; try { await api.plans.remove(plan.id); await load(); } catch (e: any) { setError(e.message); } }
  return <><PageHead title="Planes" description="Define duración y límites que el servidor aplicará a las suscripciones del Client." actions={<button className="button primary" onClick={() => setOpen(true)}><Plus size={14} />Nuevo plan</button>} /><ErrorBanner message={error} /><Card>{plans.length === 0 ? <Empty title="No hay planes" description="Crea el primer plan para poder habilitar clientes." /> : <div className="table-wrap"><table><thead><tr><th>Plan</th><th>Duración</th><th>Dispositivos</th><th>Perfiles</th><th>Estado</th><th /></tr></thead><tbody>{plans.map((p) => <tr key={p.id}><td className="table-primary">{p.name}</td><td>{p.duration_days ?? 'Sin límite'} días</td><td>{p.max_devices}</td><td>{p.max_profiles}</td><td><Badge tone={p.enabled ? 'ok' : 'bad'}>{p.enabled ? 'Activo' : 'Inactivo'}</Badge></td><td><button className="button danger small" onClick={() => remove(p)}><Trash2 size={12} />Eliminar</button></td></tr>)}</tbody></table></div>}</Card>{open && <Modal title="Nuevo plan" onClose={() => setOpen(false)} actions={<><button className="button secondary" onClick={() => setOpen(false)}>Cancelar</button><button className="button primary" form="plan-form" type="submit">Guardar</button></>}><form id="plan-form" onSubmit={submit} className="form-grid"><Field label="Nombre" className="span-2"><input className="input" name="name" required maxLength={80} /></Field><Field label="Duración (días)"><input className="input" name="durationDays" type="number" min="1" max="3650" defaultValue="30" required /></Field><Field label="Máximo de dispositivos"><input className="input" name="maxDevices" type="number" min="1" max="50" defaultValue="1" required /></Field><Field label="Máximo de perfiles"><input className="input" name="maxProfiles" type="number" min="1" max="500" defaultValue="5" required /></Field></form></Modal>}</>;
}
