import { FormEvent, useEffect, useState } from 'react';
import { Globe2, Plus, Trash2 } from 'lucide-react';
import { api } from '../api';
import type { Profile } from '../types';
import { Badge, Card, Empty, ErrorBanner, Field, Modal, PageHead } from '../components/ui';

export function ProfilesView() {
  const [profiles, setProfiles] = useState<Profile[]>([]); const [open, setOpen] = useState(false); const [error, setError] = useState<string | null>(null); async function load() { try { setProfiles(await api.profiles.list()); } catch (e: any) { setError(e.message); } } useEffect(() => { void load(); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const fd = new FormData(event.currentTarget); const tags = String(fd.get('tags') || '').split(',').map((v) => v.trim()).filter(Boolean).slice(0,20); try { await api.profiles.create({ name: String(fd.get('name') || '').trim(), url: String(fd.get('url') || '').trim(), platform: String(fd.get('platform') || '').trim() || null, image_url: String(fd.get('imageUrl') || '').trim() || null, tags, enabled: true, session_mode: String(fd.get('sessionMode')) as Profile['session_mode'] }); setOpen(false); await load(); } catch (e: any) { setError(e.message); } }
  async function remove(profile: Profile) { if (!confirm(`¿Eliminar el perfil ${profile.name}?`)) return; try { await api.profiles.remove(profile.id); await load(); } catch (e: any) { setError(e.message); } }
  return <><PageHead title="Perfiles / Webs" description="Catálogo administrado de sitios que pueden asignarse a clientes. La interfaz nunca muestra cookies ni secretos de sesión." actions={<button className="button primary" onClick={() => setOpen(true)}><Plus size={14} />Nuevo perfil</button>} /><ErrorBanner message={error} />{profiles.length === 0 ? <Card><Empty title="No hay perfiles" description="Agrega la primera web o perfil que quieras administrar." /></Card> : <div className="grid three">{profiles.map((p) => <Card className="profile-card" key={p.id}><div className="profile-image">{p.image_url ? <img src={p.image_url} alt="" referrerPolicy="no-referrer" /> : <Globe2 size={28} />}</div><div className="profile-body"><h3>{p.name}</h3><a className="profile-url" href={p.url} target="_blank" rel="noreferrer">{p.url}</a><div className="profile-tags">{p.platform && <Badge>{p.platform}</Badge>}{p.tags.map((tag) => <Badge key={tag}>{tag}</Badge>)}</div><div className="profile-actions"><Badge tone={p.enabled ? 'ok' : 'bad'}>{p.enabled ? 'Activo' : 'Inactivo'}</Badge><button className="button danger small" onClick={() => remove(p)}><Trash2 size={12} />Eliminar</button></div></div></Card>)}</div>}{open && <Modal title="Nuevo perfil / web" onClose={() => setOpen(false)} actions={<><button className="button secondary" onClick={() => setOpen(false)}>Cancelar</button><button className="button primary" form="profile-form" type="submit">Guardar</button></>}><form id="profile-form" onSubmit={submit} className="form-grid"><Field label="Nombre"><input className="input" name="name" required maxLength={100} /></Field><Field label="Plataforma"><input className="input" name="platform" maxLength={80} placeholder="Ej. Plataforma interna" /></Field><Field label="URL HTTPS" className="span-2"><input className="input" name="url" type="url" required placeholder="https://..." /></Field><Field label="Imagen (URL HTTPS)" className="span-2"><input className="input" name="imageUrl" type="url" placeholder="https://..." /></Field><Field label="Etiquetas" className="span-2" help="Separadas por coma"><input className="input" name="tags" placeholder="ventas, equipo-a" /></Field><Field label="Modo de sesión" className="span-2"><select className="select" name="sessionMode" defaultValue="manual-login"><option value="manual-login">Login manual en el Client</option><option value="managed-first-party">Sesión administrada de dominio propio</option></select></Field></form></Modal>}</>;
}
