import { FormEvent, useEffect, useState } from 'react';
import { KeyRound, Network, Plus, Trash2 } from 'lucide-react';
import { api } from '../api';
import type { ProxyRecord } from '../types';
import { Badge, Card, Empty, ErrorBanner, Field, Modal, PageHead } from '../components/ui';

export function ProxiesView() {
  const [items,setItems]=useState<ProxyRecord[]>([]); const [open,setOpen]=useState(false); const [error,setError]=useState<string|null>(null); async function load(){try{setItems(await api.proxies.list());}catch(e:any){setError(e.message);}} useEffect(()=>{void load();},[]);
  async function submit(event: FormEvent<HTMLFormElement>){event.preventDefault();const fd=new FormData(event.currentTarget);try{await api.proxies.create({name:String(fd.get('name')||'').trim(),host:String(fd.get('host')||'').trim(),port:Number(fd.get('port')),username:String(fd.get('username')||'').trim()||undefined,password:String(fd.get('password')||'')||undefined,enabled:true});setOpen(false);await load();}catch(e:any){setError(e.message);}}
  async function remove(item:ProxyRecord){if(!confirm(`¿Eliminar el proxy ${item.name}? Las asignaciones quedarán sin proxy.`))return;try{await api.proxies.remove(item.id);await load();}catch(e:any){setError(e.message);}}
  return <><PageHead title="Proxies" description="Inventario central. Las contraseñas se cifran en el Worker antes de almacenarse y nunca vuelven al navegador Admin." actions={<button className="button primary" onClick={()=>setOpen(true)}><Plus size={14}/>Nuevo proxy</button>}/><ErrorBanner message={error}/><Card>{items.length===0?<Empty title="No hay proxies" description="Agrega un proxy si algún perfil necesita una conexión administrada."/>:<div className="table-wrap"><table><thead><tr><th>Proxy</th><th>Servidor</th><th>Usuario</th><th>Clave</th><th>Estado</th><th/></tr></thead><tbody>{items.map((p)=><tr key={p.id}><td><div className="table-primary"><Network size={13} style={{verticalAlign:-2,marginRight:6}}/>{p.name}</div></td><td className="mono">{p.host}:{p.port}</td><td>{p.username||'—'}</td><td>{p.has_password?<Badge tone="ok"><KeyRound size={10}/>Cifrada</Badge>:<Badge>Sin clave</Badge>}</td><td><Badge tone={p.enabled?'ok':'bad'}>{p.enabled?'Activo':'Inactivo'}</Badge></td><td><button className="button danger small" onClick={()=>remove(p)}><Trash2 size={12}/>Eliminar</button></td></tr>)}</tbody></table></div>}</Card>{open&&<Modal title="Nuevo proxy" onClose={()=>setOpen(false)} actions={<><button className="button secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="button primary" form="proxy-form" type="submit">Guardar cifrado</button></>}><form id="proxy-form" onSubmit={submit} className="form-grid"><Field label="Nombre" className="span-2"><input className="input" name="name" required maxLength={100}/></Field><Field label="Host"><input className="input" name="host" required maxLength={255}/></Field><Field label="Puerto"><input className="input" name="port" type="number" min="1" max="65535" required/></Field><Field label="Usuario"><input className="input" name="username" autoComplete="off"/></Field><Field label="Contraseña" help="Viaja por HTTPS al Worker y se almacena cifrada."><input className="input" name="password" type="password" autoComplete="new-password"/></Field></form></Modal>}</>;
}
