import { AdminIdentity } from './auth';
import { Env, HttpError, audit, bodyJson, encryptProxy, httpsUrl, integer, iso, json, optional, passwordHash, sb, text } from './core';

async function clientDetails(env:Env,rows?:any[]){const clients=rows||await sb(env,'userflex_clients?select=id,name,email,phone,status,created_at,updated_at&order=created_at.desc');if(!clients?.length)return[];const ids=clients.map((c:any)=>c.id).join(',');const creds=await sb(env,`userflex_client_credentials?select=client_id,username,password_hash&client_id=in.(${ids})`);const subs=await sb(env,`userflex_subscriptions?select=id,client_id,plan_id,starts_at,expires_at,status,offline_grace_minutes,created_at,updated_at&client_id=in.(${ids})&order=created_at.desc`);const planIds=[...new Set((subs||[]).map((s:any)=>s.plan_id))];const plans=planIds.length?await sb(env,`userflex_plans?select=id,name,duration_days,max_devices,max_profiles,enabled,created_at,updated_at&id=in.(${planIds.join(',')})`):[];const pm=new Map(plans.map((p:any)=>[p.id,p]));return clients.map((c:any)=>{const credential=creds.find((x:any)=>x.client_id===c.id);const subscription=subs.find((s:any)=>s.client_id===c.id&&s.status==='active')||subs.find((s:any)=>s.client_id===c.id)||null;return{...c,credential:credential?{username:credential.username,has_password:Boolean(credential.password_hash)}:null,subscription:subscription?{...subscription,plan:pm.get(subscription.plan_id)||null}:null}})}
function safeProxy(p:any){return{id:p.id,name:p.name,host:p.host,port:p.port,username:p.username||null,enabled:p.enabled===true,has_password:Boolean(p.password_ciphertext),created_at:p.created_at,updated_at:p.updated_at}}

export async function adminRoutes(request:Request,env:Env,admin:AdminIdentity):Promise<Response>{const url=new URL(request.url),path=url.pathname,method=request.method.toUpperCase();
  if(path==='/api/dashboard'&&method==='GET'){const [clients,plans,profiles,proxies,devices,assignments]=await Promise.all([sb(env,'userflex_clients?select=id,status'),sb(env,'userflex_plans?select=id'),sb(env,'userflex_profiles?select=id'),sb(env,'userflex_proxies?select=id'),sb(env,'userflex_devices?select=id,status'),sb(env,'userflex_assignments?select=id')]);return json({clients:clients.length,activeClients:clients.filter((c:any)=>c.status==='active').length,plans:plans.length,profiles:profiles.length,proxies:proxies.length,devices:devices.length,activeDevices:devices.filter((d:any)=>d.status==='active').length,assignments:assignments.length})}

  if(path==='/api/clients'&&method==='GET')return json(await clientDetails(env));
  if(path==='/api/clients'&&method==='POST'){const b=await bodyJson(request),name=text(b.name,'name',120),email=text(b.email,'email',200).toLowerCase(),phone=optional(b.phone,40),planId=text(b.planId,'planId',36),username=text(b.username,'username',80).toLowerCase(),startsAt=iso(b.startsAt,'startsAt'),expiresAt=iso(b.expiresAt,'expiresAt');if(!/^\S+@\S+\.\S+$/.test(email))throw new HttpError(400,'INVALID_EMAIL');if(new Date(expiresAt)<=new Date(startsAt))throw new HttpError(400,'INVALID_SUBSCRIPTION_RANGE');const password_hash=await passwordHash(typeof b.password==='string'?b.password:'');const result=await sb(env,'rpc/userflex_create_client',{method:'POST',body:JSON.stringify({p_name:name,p_email:email,p_phone:phone,p_plan_id:planId,p_username:username,p_password_hash:password_hash,p_starts_at:startsAt,p_expires_at:expiresAt})});const id=Array.isArray(result)?result[0]:result;await audit(env,request,'admin',admin.userId,'client.create','client',String(id));const rows=await sb(env,`userflex_clients?select=id,name,email,phone,status,created_at,updated_at&id=eq.${id}&limit=1`);return json((await clientDetails(env,rows))[0],201)}
  const creds=path.match(/^\/api\/clients\/([0-9a-f-]{36})\/credentials$/i);if(creds&&method==='POST'){const b=await bodyJson(request),username=text(b.username,'username',80).toLowerCase(),password_hash=await passwordHash(typeof b.password==='string'?b.password:'');await sb(env,'userflex_client_credentials?on_conflict=client_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({client_id:creds[1],username,password_hash,updated_at:new Date().toISOString()})});await sb(env,`userflex_client_sessions?client_id=eq.${creds[1]}&revoked_at=is.null`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({revoked_at:new Date().toISOString()})});await audit(env,request,'admin',admin.userId,'client.credentials.reset','client',creds[1]);return json({ok:true,username})}
  const sub=path.match(/^\/api\/clients\/([0-9a-f-]{36})\/subscription$/i);if(sub&&method==='POST'){const b=await bodyJson(request),planId=text(b.planId,'planId',36),startsAt=iso(b.startsAt,'startsAt'),expiresAt=iso(b.expiresAt,'expiresAt');if(new Date(expiresAt)<=new Date(startsAt))throw new HttpError(400,'INVALID_SUBSCRIPTION_RANGE');await sb(env,`userflex_subscriptions?client_id=eq.${sub[1]}&status=eq.active`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'cancelled',updated_at:new Date().toISOString()})});await sb(env,'userflex_subscriptions',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({client_id:sub[1],plan_id:planId,starts_at:startsAt,expires_at:expiresAt,status:'active',offline_grace_minutes:0})});await sb(env,`userflex_client_sessions?client_id=eq.${sub[1]}&revoked_at=is.null`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({revoked_at:new Date().toISOString()})});await audit(env,request,'admin',admin.userId,'client.subscription.update','client',sub[1],{planId,expiresAt});return json({ok:true})}
  const client=path.match(/^\/api\/clients\/([0-9a-f-]{36})$/i);if(client&&method==='PATCH'){const b=await bodyJson(request),patch:any={updated_at:new Date().toISOString()};if(b.name!==undefined)patch.name=text(b.name,'name',120);if(b.email!==undefined){patch.email=text(b.email,'email',200).toLowerCase();if(!/^\S+@\S+\.\S+$/.test(patch.email))throw new HttpError(400,'INVALID_EMAIL')}if(b.phone!==undefined)patch.phone=optional(b.phone,40);if(b.status!==undefined){if(!['active','suspended'].includes(b.status))throw new HttpError(400,'INVALID_STATUS');patch.status=b.status}const rows=await sb(env,`userflex_clients?id=eq.${client[1]}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});if(!rows?.[0])throw new HttpError(404,'CLIENT_NOT_FOUND');if(patch.status==='suspended')await sb(env,`userflex_client_sessions?client_id=eq.${client[1]}&revoked_at=is.null`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({revoked_at:new Date().toISOString()})});await audit(env,request,'admin',admin.userId,'client.update','client',client[1]);return json((await clientDetails(env,rows))[0])}if(client&&method==='DELETE'){await sb(env,`userflex_clients?id=eq.${client[1]}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});await audit(env,request,'admin',admin.userId,'client.delete','client',client[1]);return json({ok:true})}

  if(path==='/api/plans'&&method==='GET')return json(await sb(env,'userflex_plans?select=id,name,duration_days,max_devices,max_profiles,enabled,created_at,updated_at&order=name.asc'));
  if(path==='/api/plans'&&method==='POST'){const b=await bodyJson(request),row={name:text(b.name,'name',80),duration_days:b.duration_days===null?null:integer(b.duration_days,1,3650,'duration_days'),max_devices:integer(b.max_devices,1,50,'max_devices'),max_profiles:integer(b.max_profiles,1,500,'max_profiles'),enabled:b.enabled!==false};const rows=await sb(env,'userflex_plans',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});await audit(env,request,'admin',admin.userId,'plan.create','plan',rows[0].id);return json(rows[0],201)}
  const plan=path.match(/^\/api\/plans\/([0-9a-f-]{36})$/i);if(plan&&method==='DELETE'){await sb(env,`userflex_plans?id=eq.${plan[1]}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});await audit(env,request,'admin',admin.userId,'plan.delete','plan',plan[1]);return json({ok:true})}

  if(path==='/api/profiles'&&method==='GET')return json(await sb(env,'userflex_profiles?select=id,name,url,platform,image_url,tags,enabled,session_mode,session_ready,created_at,updated_at&order=name.asc'));
  if(path==='/api/profiles'&&method==='POST'){const b=await bodyJson(request),mode=['manual-login','managed-first-party'].includes(b.session_mode)?b.session_mode:'manual-login',row={name:text(b.name,'name',100),url:httpsUrl(b.url,'url'),platform:optional(b.platform,80),image_url:httpsUrl(b.image_url,'image_url',true),tags:Array.isArray(b.tags)?b.tags.filter((x:any)=>typeof x==='string').map((x:string)=>x.trim()).filter(Boolean).slice(0,20):[],enabled:b.enabled!==false,session_mode:mode,session_ready:false};const rows=await sb(env,'userflex_profiles',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});await audit(env,request,'admin',admin.userId,'profile.create','profile',rows[0].id);return json(rows[0],201)}
  const profile=path.match(/^\/api\/profiles\/([0-9a-f-]{36})$/i);if(profile&&method==='DELETE'){await sb(env,`userflex_profiles?id=eq.${profile[1]}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});await audit(env,request,'admin',admin.userId,'profile.delete','profile',profile[1]);return json({ok:true})}

  if(path==='/api/proxies'&&method==='GET')return json((await sb(env,'userflex_proxies?select=id,name,host,port,username,password_ciphertext,enabled,created_at,updated_at&order=name.asc')).map(safeProxy));
  if(path==='/api/proxies'&&method==='POST'){const b=await bodyJson(request),row:any={name:text(b.name,'name',100),host:text(b.host,'host',255),port:integer(b.port,1,65535,'port'),username:optional(b.username,160),enabled:b.enabled!==false};if(b.password){const secret=await encryptProxy(env,text(b.password,'password',512));Object.assign(row,{password_ciphertext:secret.ciphertext,password_iv:secret.iv,key_version:secret.keyVersion})}const rows=await sb(env,'userflex_proxies',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});await audit(env,request,'admin',admin.userId,'proxy.create','proxy',rows[0].id,{host:rows[0].host,port:rows[0].port,hasPassword:Boolean(rows[0].password_ciphertext)});return json(safeProxy(rows[0]),201)}
  const proxy=path.match(/^\/api\/proxies\/([0-9a-f-]{36})$/i);if(proxy&&method==='DELETE'){await sb(env,`userflex_proxies?id=eq.${proxy[1]}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});await audit(env,request,'admin',admin.userId,'proxy.delete','proxy',proxy[1]);return json({ok:true})}

  if(path==='/api/assignments'&&method==='GET'){const rows=await sb(env,'userflex_assignments?select=id,client_id,profile_id,proxy_id,enabled,created_at,updated_at&order=created_at.desc');const ci=[...new Set(rows.map((r:any)=>r.client_id))],pi=[...new Set(rows.map((r:any)=>r.profile_id))],xi=[...new Set(rows.map((r:any)=>r.proxy_id).filter(Boolean))];const [cs,ps,xs]=await Promise.all([ci.length?sb(env,`userflex_clients?select=id,name,email&id=in.(${ci.join(',')})`):[],pi.length?sb(env,`userflex_profiles?select=id,name,url&id=in.(${pi.join(',')})`):[],xi.length?sb(env,`userflex_proxies?select=id,name,host,port&id=in.(${xi.join(',')})`):[]]);const cm=new Map(cs.map((x:any)=>[x.id,x])),pm=new Map(ps.map((x:any)=>[x.id,x])),xm=new Map(xs.map((x:any)=>[x.id,x]));return json(rows.map((r:any)=>({...r,client:cm.get(r.client_id),profile:pm.get(r.profile_id),proxy:r.proxy_id?xm.get(r.proxy_id)||null:null})))}
  if(path==='/api/assignments'&&method==='POST'){const b=await bodyJson(request),clientId=text(b.clientId,'clientId',36),profileId=text(b.profileId,'profileId',36),proxyId=optional(b.proxyId,36),enabled=b.enabled!==false;const result=await sb(env,'rpc/userflex_upsert_assignment',{method:'POST',body:JSON.stringify({p_client_id:clientId,p_profile_id:profileId,p_proxy_id:proxyId,p_enabled:enabled})});const id=Array.isArray(result)?result[0]:result,rows=await sb(env,`userflex_assignments?select=id,client_id,profile_id,proxy_id,enabled,created_at,updated_at&id=eq.${id}&limit=1`);await audit(env,request,'admin',admin.userId,'assignment.upsert','assignment',id,{clientId,profileId,proxyAssigned:Boolean(proxyId)});return json(rows[0],201)}
  const assignment=path.match(/^\/api\/assignments\/([0-9a-f-]{36})$/i);if(assignment&&method==='DELETE'){await sb(env,`userflex_assignments?id=eq.${assignment[1]}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});await audit(env,request,'admin',admin.userId,'assignment.delete','assignment',assignment[1]);return json({ok:true})}

  if(path==='/api/devices'&&method==='GET'){const rows=await sb(env,'userflex_devices?select=id,client_id,name,os,status,last_seen_at,created_at&order=last_seen_at.desc.nullslast'),ids=[...new Set(rows.map((r:any)=>r.client_id))],clients=ids.length?await sb(env,`userflex_clients?select=id,name,email&id=in.(${ids.join(',')})`):[],cm=new Map(clients.map((x:any)=>[x.id,x]));return json(rows.map((r:any)=>({...r,client:cm.get(r.client_id)})))}
  const revoke=path.match(/^\/api\/devices\/([0-9a-f-]{36})\/revoke$/i);if(revoke&&method==='POST'){const rows=await sb(env,`userflex_devices?id=eq.${revoke[1]}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({status:'revoked',updated_at:new Date().toISOString()})}),device=rows?.[0];if(!device)throw new HttpError(404,'DEVICE_NOT_FOUND');await sb(env,`userflex_client_sessions?device_id=eq.${device.id}&revoked_at=is.null`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({revoked_at:new Date().toISOString()})});await audit(env,request,'admin',admin.userId,'device.revoke','device',device.id,{clientId:device.client_id});return json(device)}

  if(path==='/api/audit'&&method==='GET'){const limit=Math.min(Math.max(Number(url.searchParams.get('limit')||100),1),500);return json(await sb(env,`userflex_audit_logs?select=id,actor_type,actor_id,action,entity_type,entity_id,ip_hash,details,created_at&order=created_at.desc&limit=${limit}`))}
  throw new HttpError(404,'NOT_FOUND');
}
