import { ADMIN_COOKIE, CLIENT_SESSION_SECONDS, DEFAULT_AUTH_ORIGIN, Env, HttpError, adminCookie, audit, bodyJson, clearAdminCookie, cookie, json, loginGuard, passwordVerify, resetGuard, sb, sha, text, token } from './core';

export type AdminIdentity={userId:string;username:string;sessionId:string};
export type ClientIdentity={clientId:string;deviceId:string;sessionId:string;plan:any;subscription:any};

export async function requireAdmin(request:Request,env:Env):Promise<AdminIdentity>{const raw=cookie(request,ADMIN_COOKIE);if(!raw||raw.length<32||raw.length>128)throw new HttpError(401,'UNAUTHENTICATED');const hash=await sha(raw);const rows=await sb(env,`vsixteen_login_sessions?select=id,user_id,expires_at&token_hash=eq.${hash}&revoked_at=is.null&expires_at=gt.${encodeURIComponent(new Date().toISOString())}&limit=1`);const session=rows?.[0];if(!session)throw new HttpError(401,'UNAUTHENTICATED');const users=await sb(env,`vsixteen_users?select=id,username,enabled&id=eq.${session.user_id}&enabled=eq.true&limit=1`);const user=users?.[0];if(!user)throw new HttpError(401,'UNAUTHENTICATED');void sb(env,`vsixteen_login_sessions?id=eq.${session.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({last_seen_at:new Date().toISOString()})}).catch(()=>{});return{userId:user.id,username:user.username,sessionId:session.id}}

export async function adminLogin(request:Request,env:Env){const guard=await loginGuard(env,request,'admin');const body=await bodyJson(request,16384);const username=text(body.username,'username',120),password=typeof body.password==='string'?body.password:'';if(!password||password.length>512)throw new HttpError(400,'INVALID_CREDENTIALS');const origin=(env.CREATORTOOLS_AUTH_ORIGIN||DEFAULT_AUTH_ORIGIN).replace(/\/$/,'');const upstream=await fetch(`${origin}/api/auth/login`,{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({username,password}),redirect:'manual'});if(!upstream.ok){if([400,401,403].includes(upstream.status))throw new HttpError(401,'INVALID_CREDENTIALS');throw new HttpError(503,'AUTH_BACKEND_UNAVAILABLE')}const setCookie=upstream.headers.get('set-cookie')||'';const match=setCookie.match(/ct_session=([^;]+)/i);if(!match)throw new HttpError(503,'AUTH_SESSION_MISSING');const raw=decodeURIComponent(match[1]);await resetGuard(env,guard);const hash=await sha(raw);const sessions=await sb(env,`vsixteen_login_sessions?select=user_id&token_hash=eq.${hash}&limit=1`),userId=sessions?.[0]?.user_id;if(!userId)throw new HttpError(503,'AUTH_SESSION_MISSING');const users=await sb(env,`vsixteen_users?select=id,username&id=eq.${userId}&limit=1`),user=users?.[0];if(!user)throw new HttpError(503,'AUTH_SESSION_MISSING');await audit(env,request,'admin',user.id,'admin.login');return json({ok:true,user:{username:user.username}},200,{'Set-Cookie':adminCookie(raw)})}

export async function adminLogout(request:Request,env:Env){const raw=cookie(request,ADMIN_COOKIE);if(raw){const hash=await sha(raw);await sb(env,`vsixteen_login_sessions?token_hash=eq.${hash}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({revoked_at:new Date().toISOString()})})}return json({ok:true},200,{'Set-Cookie':clearAdminCookie()})}

export async function entitlement(env:Env,clientId:string){const now=encodeURIComponent(new Date().toISOString());const rows=await sb(env,`userflex_subscriptions?select=id,client_id,plan_id,starts_at,expires_at,status,offline_grace_minutes&client_id=eq.${clientId}&status=eq.active&starts_at=lte.${now}&expires_at=gt.${now}&order=expires_at.desc&limit=1`);const subscription=rows?.[0];if(!subscription)throw new HttpError(403,'SUBSCRIPTION_INACTIVE','La suscripción no está activa.');const plans=await sb(env,`userflex_plans?select=id,name,duration_days,max_devices,max_profiles,enabled&id=eq.${subscription.plan_id}&enabled=eq.true&limit=1`),plan=plans?.[0];if(!plan)throw new HttpError(403,'PLAN_INACTIVE','El plan no está activo.');return{subscription,plan}}

export async function requireClient(request:Request,env:Env):Promise<ClientIdentity>{const match=(request.headers.get('authorization')||'').match(/^Bearer\s+([A-Za-z0-9_-]{32,128})$/);if(!match)throw new HttpError(401,'CLIENT_UNAUTHENTICATED');const hash=await sha(match[1]);const now=encodeURIComponent(new Date().toISOString());const sessions=await sb(env,`userflex_client_sessions?select=id,client_id,device_id&token_hash=eq.${hash}&revoked_at=is.null&expires_at=gt.${now}&limit=1`),session=sessions?.[0];if(!session)throw new HttpError(401,'CLIENT_UNAUTHENTICATED');const clients=await sb(env,`userflex_clients?select=id&id=eq.${session.client_id}&status=eq.active&limit=1`);if(!clients?.[0])throw new HttpError(403,'CLIENT_SUSPENDED');const devices=await sb(env,`userflex_devices?select=id&id=eq.${session.device_id}&client_id=eq.${session.client_id}&status=eq.active&limit=1`);if(!devices?.[0])throw new HttpError(403,'DEVICE_REVOKED');const {subscription,plan}=await entitlement(env,session.client_id);const stamp=new Date().toISOString();void sb(env,`userflex_client_sessions?id=eq.${session.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({last_seen_at:stamp})}).catch(()=>{});void sb(env,`userflex_devices?id=eq.${session.device_id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({last_seen_at:stamp})}).catch(()=>{});return{clientId:session.client_id,deviceId:session.device_id,sessionId:session.id,plan,subscription}}

export async function clientLogin(request:Request,env:Env){const body=await bodyJson(request,24576);const identifier=text(body.identifier,'identifier',160).toLowerCase();const guard=await loginGuard(env,request,'client',identifier);const password=typeof body.password==='string'?body.password:'';const deviceKey=text(body.deviceKey,'deviceKey',512),deviceName=text(body.deviceName,'deviceName',120),os=typeof body.os==='string'?body.os.trim().slice(0,120):null;if(!password||password.length>256)throw new HttpError(401,'INVALID_CLIENT_CREDENTIALS');let rows=await sb(env,`userflex_client_credentials?select=client_id,username,password_hash&username=eq.${encodeURIComponent(identifier)}&limit=1`),cred=rows?.[0];if(!cred){const c=await sb(env,`userflex_clients?select=id&email=eq.${encodeURIComponent(identifier)}&limit=1`);if(c?.[0]){rows=await sb(env,`userflex_client_credentials?select=client_id,username,password_hash&client_id=eq.${c[0].id}&limit=1`);cred=rows?.[0]}}if(!cred||!(await passwordVerify(password,cred.password_hash)))throw new HttpError(401,'INVALID_CLIENT_CREDENTIALS');await resetGuard(env,guard);const clients=await sb(env,`userflex_clients?select=id,name,email,status&id=eq.${cred.client_id}&limit=1`),client=clients?.[0];if(!client||client.status!=='active')throw new HttpError(403,'CLIENT_SUSPENDED');const {subscription,plan}=await entitlement(env,client.id);const deviceHash=await sha(`userflex-device:${deviceKey}`);const registered=await sb(env,'rpc/userflex_register_device',{method:'POST',body:JSON.stringify({p_client_id:client.id,p_device_hash:deviceHash,p_name:deviceName,p_os:os,p_max_devices:plan.max_devices})});const device=Array.isArray(registered)?registered[0]:registered;if(!device)throw new HttpError(503,'DEVICE_REGISTRATION_FAILED');if(device.status==='revoked')throw new HttpError(403,'DEVICE_REVOKED');if(device.status==='limit_reached')throw new HttpError(403,'DEVICE_LIMIT_REACHED','Se alcanzó el máximo de dispositivos del plan.');const raw=token(),hash=await sha(raw),expiresAt=new Date(Date.now()+CLIENT_SESSION_SECONDS*1000).toISOString();await sb(env,'userflex_client_sessions',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({client_id:client.id,device_id:device.id,token_hash:hash,expires_at:expiresAt,last_seen_at:new Date().toISOString()})});await audit(env,request,'client',client.id,'client.login','device',device.id,{username:cred.username});return json({ok:true,accessToken:raw,expiresAt,client:{id:client.id,name:client.name,email:client.email},plan:{id:plan.id,name:plan.name},subscription:{expiresAt:subscription.expires_at}})}
