import { ClientIdentity } from './auth';
import { Env, HttpError, audit, decryptProxy, json, sb } from './core';

export async function clientCatalog(env:Env,id:ClientIdentity){const assignments=await sb(env,`userflex_assignments?select=id,profile_id,proxy_id&client_id=eq.${id.clientId}&enabled=eq.true&order=created_at.asc`);if(!assignments?.length)return json({ok:true,profiles:[],plan:{id:id.plan.id,name:id.plan.name},expiresAt:id.subscription.expires_at});const limited=assignments.slice(0,id.plan.max_profiles),ids=limited.map((a:any)=>a.profile_id).join(',');const profiles=await sb(env,`userflex_profiles?select=id,name,url,platform,image_url,tags,enabled,session_mode,session_ready&id=in.(${ids})&enabled=eq.true`),map=new Map((profiles||[]).map((p:any)=>[p.id,p]));const result=limited.map((a:any)=>{const p:any=map.get(a.profile_id);return p?{id:p.id,name:p.name,url:p.url,platform:p.platform,imageUrl:p.image_url,tags:p.tags||[],managedConnection:Boolean(a.proxy_id),sessionMode:p.session_mode,sessionReady:p.session_ready===true}:null}).filter(Boolean);return json({ok:true,profiles:result,plan:{id:id.plan.id,name:id.plan.name},expiresAt:id.subscription.expires_at})}

export async function clientLaunch(request:Request,env:Env,id:ClientIdentity,profileId:string){const assignments=await sb(env,`userflex_assignments?select=id,proxy_id&client_id=eq.${id.clientId}&profile_id=eq.${profileId}&enabled=eq.true&limit=1`),assignment=assignments?.[0];if(!assignment)throw new HttpError(403,'PROFILE_NOT_ASSIGNED');const profiles=await sb(env,`userflex_profiles?select=id,name,url,platform,image_url,tags,session_mode,session_ready&id=eq.${profileId}&enabled=eq.true&limit=1`),p=profiles?.[0];if(!p)throw new HttpError(404,'PROFILE_NOT_FOUND');let connection:any={mode:'direct'};if(assignment.proxy_id){const rows=await sb(env,`userflex_proxies?select=id,host,port,username,password_ciphertext,password_iv&enabled=eq.true&id=eq.${assignment.proxy_id}&limit=1`),proxy=rows?.[0];if(proxy)connection={mode:'proxy',proxy:{host:proxy.host,port:proxy.port,username:proxy.username||null,password:proxy.password_ciphertext?await decryptProxy(env,proxy.password_ciphertext,proxy.password_iv):null}}}await audit(env,request,'client',id.clientId,'profile.launch','profile',profileId,{deviceId:id.deviceId,usesProxy:connection.mode==='proxy'});return json({ok:true,lease:{expiresAt:id.subscription.expires_at,serverTime:new Date().toISOString()},profile:{id:p.id,name:p.name,url:p.url,platform:p.platform,imageUrl:p.image_url,tags:p.tags||[],sessionMode:p.session_mode,sessionReady:p.session_ready===true},connection,sessionDelivery:{ready:p.session_ready===true,mode:p.session_mode,materialIncluded:false}})}

export async function clientHeartbeat(id:ClientIdentity){return json({ok:true,active:true,revoke:false,plan:{id:id.plan.id,name:id.plan.name},expiresAt:id.subscription.expires_at,serverTime:new Date().toISOString()})}
export async function clientLogout(env:Env,id:ClientIdentity){await sb(env,`userflex_client_sessions?id=eq.${id.sessionId}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({revoked_at:new Date().toISOString()})});return json({ok:true})}
