import test from 'node:test';
import assert from 'node:assert/strict';
import {createDesktopBridge, publicCatalog, authorize, validateCookies} from './desktop-bridge.mjs';
const now = Date.parse('2026-09-08T12:00:00Z');
const cookie = {name:'session',value:'fictional',domain:'example.test',secure:true,httpOnly:true,expirationDate:now/1000+3600};
const data = {clients:[
 {id:'a',name:'Alice',status:'active',subscription:{plan:'test',end:'2026-10-01'},modules:{m:true},profileIds:['p'],devices:[{id:'device-a',status:'active'}]},
 {id:'b',name:'Bob',status:'active',subscription:{plan:'test',end:'2026-10-01'},modules:{m:true},profileIds:['q'],devices:[{id:'device-b',status:'active'}]}],
 modules:[{id:'m',name:'Example',enabled:true,profiles:[{id:'p',name:'A',url:'https://example.test/a',credentialOk:true},{id:'q',name:'B',url:'https://example.test/b',credentialOk:true}]}]};
function fixture() {
 const records=new Map(), vault={clientId:'a',moduleId:'m',approved:true,source:'admin-verified',profileId:'p',url:'https://example.test/a',expiresAt:'2026-09-09',cookies:[cookie],version:'1'};
 const sessions={put:async(k,v)=>records.set(k,v),get:async k=>records.get(k),revoke:async k=>{records.get(k).revoked=true}};
 const bridge=createDesktopBridge({authenticate:async({identifier,deviceId,password})=> password==='correct' ? {clientId:identifier,deviceId}:null,sessions,readData:async()=>data,readBundle:async()=>vault,now:()=>now});
 return {bridge,vault};
}
test('catalog only includes explicitly assigned profiles and no secrets',()=>{const c=publicCatalog(data,'a',now);assert.deepEqual(c.modules[0].profiles.map(p=>p.id),['p']);assert.equal(JSON.stringify(c).includes('fictional'),false);assert.equal(JSON.stringify(c).includes('password'),false)});
test('missing assignment, disabled module and expired subscription deny access',()=>{assert.throws(()=>authorize(data,'a','m','q',now));const d=structuredClone(data);d.clients[0].modules.m=false;assert.throws(()=>authorize(d,'a','m','p',now));d.clients[0].modules.m=true;d.clients[0].subscription.end='2026-01-01';assert.throws(()=>authorize(d,'a',null,null,now));});
test('login needs credentials and an approved device',async()=>{const {bridge}=fixture();await assert.rejects(bridge.login({identifier:'a',password:'wrong',deviceId:'device-a'}));await assert.rejects(bridge.login({identifier:'a',password:'correct',deviceId:'device-b'}));const r=await bridge.login({identifier:'a',password:'correct',deviceId:'device-a'});assert.ok(r.token.length>40);});
test('tokens are device-bound, revocable and do not reveal other profiles',async()=>{const {bridge}=fixture();const {token}=await bridge.login({identifier:'a',password:'correct',deviceId:'device-a'});await assert.rejects(bridge.catalog(token,'device-b'));await assert.rejects(bridge.bundle(token,'device-a','m','q'));const b=await bridge.bundle(token,'device-a','m','p');assert.equal(b.cookies[0].value,'fictional');await bridge.logout(token,'device-a');await assert.rejects(bridge.catalog(token,'device-a'));});
test('permission and device revocation take effect on the next request',async()=>{const {bridge}=fixture();const {token}=await bridge.login({identifier:'a',password:'correct',deviceId:'device-a'});data.clients[0].profileIds=[];await assert.rejects(bridge.bundle(token,'device-a','m','p'));data.clients[0].devices[0].status='revoked';await assert.rejects(bridge.catalog(token,'device-a'));data.clients[0].profileIds=['p'];data.clients[0].devices[0].status='active';});
test('unapproved or expired vault entries never deliver cookies',async()=>{const {bridge,vault}=fixture();const {token}=await bridge.login({identifier:'a',password:'correct',deviceId:'device-a'});vault.approved=false;await assert.rejects(bridge.bundle(token,'device-a','m','p'));vault.approved=true;vault.expiresAt='2026-01-01';await assert.rejects(bridge.bundle(token,'device-a','m','p'));vault.expiresAt='2026-09-09';vault.source='simulated';await assert.rejects(bridge.bundle(token,'device-a','m','p'));});
test('cookie validation rejects unrelated domains, expiration and insecure cookies',()=>{assert.throws(()=>validateCookies([{...cookie,domain:'other.test'}],'https://example.test',now));assert.throws(()=>validateCookies([{...cookie,expirationDate:1}],'https://example.test',now));assert.throws(()=>validateCookies([{...cookie,secure:false}],'https://example.test',now));assert.throws(()=>validateCookies([cookie,cookie],'https://example.test',now));assert.equal(validateCookies([cookie],'https://example.test',now)[0].httpOnly,true);});
test('parent-domain cookies require an explicit administrator allowlist',()=>{const c={...cookie,domain:'.example.test'};assert.equal(validateCookies([c],'https://example.test',now).length,1);assert.throws(()=>validateCookies([c],'https://app.example.test',now));assert.equal(validateCookies([c],'https://app.example.test',now,['example.test']).length,1);});
