import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';import path from 'node:path';
import {randomBytes,randomUUID,createCipheriv,createDecipheriv,scryptSync,timingSafeEqual,createHash} from 'node:crypto';
import {BridgeError,cleanUrl,validateCookies} from './cookie-policy.mjs';
const fail=(code,message)=>{throw new BridgeError(code,message);};
const hashToken=s=>createHash('sha256').update(s).digest('hex');
const json=v=>JSON.stringify(v),parse=v=>JSON.parse(v);
const id=s=>typeof s==='string'&&/^[a-zA-Z0-9_-]{1,100}$/.test(s);
const date=s=>typeof s==='string'&&Number.isFinite(Date.parse(s));
export function hashPassword(password){if(typeof password!=='string'||password.length<12||password.length>1024)fail(400,'Password must have at least 12 characters');const salt=randomBytes(16);const hash=scryptSync(password,salt,64,{N:16384,r:8,p:1,maxmem:64*1024*1024});return `scrypt$16384$${salt.toString('base64url')}$${hash.toString('base64url')}`;}
export function verifyPassword(password,encoded){if(typeof password!=='string'||password.length>1024||typeof encoded!=='string')return false;const parts=encoded.split('$');if(parts.length!==4||parts[0]!=='scrypt'||parts[1]!=='16384')return false;try{const salt=Buffer.from(parts[2],'base64url'),expected=Buffer.from(parts[3],'base64url');if(salt.length!==16||expected.length!==64)return false;const actual=scryptSync(password,salt,64,{N:16384,r:8,p:1,maxmem:64*1024*1024});return timingSafeEqual(actual,expected);}catch{return false;}}
function metadata(input){const modules=(input.modules||[]).map(m=>({id:m.id,name:m.name,icon:m.icon||'',category:m.category||'web',enabled:m.enabled===true,profiles:(m.profiles||[]).map(p=>({id:p.id,name:p.name,url:cleanUrl(p.url).href,credentialOk:p.credentialOk===true,allowedCookieDomains:p.allowedCookieDomains||[]}))}));const clients=(input.clients||[]).map(c=>({id:c.id,name:c.name,status:c.status,subscription:{plan:c.subscription?.plan||'',end:c.subscription?.end},modules:c.modules||{},profileIds:c.profileIds||[],devices:(c.devices||[]).map(d=>({id:d.id,status:d.status}))}));for(const c of clients){if(!id(c.id)||!date(c.subscription.end)||!['active','suspended'].includes(c.status))fail(400,'Invalid client');if(!Array.isArray(c.profileIds)||!c.profileIds.every(id))fail(400,'Invalid assignments');}const moduleIds=new Set(),profileIds=new Set();for(const m of modules){if(moduleIds.has(m.id))fail(400,'Duplicate module');moduleIds.add(m.id);if(!id(m.id)||typeof m.name!=='string'||!Array.isArray(m.profiles))fail(400,'Invalid module');for(const p of m.profiles){if(!id(p.id)||!p.name||!Array.isArray(p.allowedCookieDomains)||profileIds.has(p.id))fail(400,'Invalid profile');profileIds.add(p.id);}}return {clients,modules};}
// Single-host staging adapter. Use a shared transactional database for production/multiple instances.
export class DurableBridgeStore{
 constructor({filename,key,now=Date.now}){if(!filename||!Buffer.isBuffer(key)||key.length!==32)throw new Error('A durable database path and 32-byte vault key are required');fs.mkdirSync(path.dirname(filename),{recursive:true,mode:0o700});this.db=new DatabaseSync(filename);fs.chmodSync(filename,0o600);this.key=Buffer.from(key);this.now=now;this.db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
 CREATE TABLE IF NOT EXISTS state(id INTEGER PRIMARY KEY CHECK(id=1),data TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS credentials(id TEXT PRIMARY KEY,username TEXT UNIQUE NOT NULL,hash TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS admins(username TEXT PRIMARY KEY,hash TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS admin_tokens(hash TEXT PRIMARY KEY,expires INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS devices(id TEXT PRIMARY KEY,client_id TEXT NOT NULL,public_key TEXT NOT NULL,status TEXT NOT NULL,created INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS sessions(hash TEXT PRIMARY KEY,data TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS vault(client_id TEXT NOT NULL,module_id TEXT NOT NULL,profile_id TEXT NOT NULL,version TEXT NOT NULL,expires TEXT NOT NULL,ciphertext TEXT NOT NULL,PRIMARY KEY(client_id,module_id,profile_id));
 CREATE TABLE IF NOT EXISTS nonces(device_id TEXT NOT NULL,nonce TEXT NOT NULL,expires INTEGER NOT NULL,PRIMARY KEY(device_id,nonce));
 CREATE TABLE IF NOT EXISTS audit(id TEXT PRIMARY KEY,at TEXT NOT NULL,action TEXT NOT NULL,subject TEXT NOT NULL,details TEXT NOT NULL);`);this.db.prepare('INSERT OR IGNORE INTO state(id,data) VALUES(1,?)').run(json({clients:[],modules:[]}));this.sessions={put:async(k,v)=>this.db.prepare('INSERT OR REPLACE INTO sessions VALUES(?,?)').run(k,json(v)),get:async k=>{const r=this.db.prepare('SELECT data FROM sessions WHERE hash=?').get(k);return r?parse(r.data):null;},revoke:async k=>this.db.prepare('DELETE FROM sessions WHERE hash=?').run(k)};}
 close(){this.db.close();this.key.fill(0);}
 readData(){const data=parse(this.db.prepare('SELECT data FROM state WHERE id=1').get().data);for(const c of data.clients)c.devices=this.db.prepare('SELECT id,status FROM devices WHERE client_id=?').all(c.id);return data;}
 saveData(input){const next=metadata(input);this.db.prepare('UPDATE state SET data=? WHERE id=1').run(json(next));return next;}
 setCredential(clientId,username,password){if(!id(clientId)||!id(username))fail(400,'Invalid account');const hash=hashPassword(password);this.db.prepare('INSERT INTO credentials VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET username=excluded.username,hash=excluded.hash').run(clientId,username.toLowerCase(),hash);this.revokeClient(clientId);}
 authenticate({identifier,password,deviceId}){const r=this.db.prepare('SELECT * FROM credentials WHERE username=?').get(String(identifier||'').toLowerCase());if(!r||!verifyPassword(password,r.hash))return null;return {clientId:r.id,deviceId};}
 bootstrapAdmin(username,password){if(!id(username))fail(400,'Invalid admin');const hash=hashPassword(password);if(this.db.prepare('SELECT COUNT(*) AS n FROM admins').get().n)throw new Error('Administrator already exists');this.db.prepare('INSERT INTO admins VALUES(?,?)').run(username.toLowerCase(),hash);}
 adminLogin(username,password){const r=this.db.prepare('SELECT hash FROM admins WHERE username=?').get(String(username||'').toLowerCase());if(!r||!verifyPassword(password,r.hash))fail(401,'Invalid credentials');const token=randomBytes(32).toString('base64url');this.db.prepare('INSERT INTO admin_tokens VALUES(?,?)').run(hashToken(token),this.now()+15*60_000);return {token};}
 requireAdmin(token){const r=this.db.prepare('SELECT expires FROM admin_tokens WHERE hash=?').get(hashToken(token||''));if(!r||r.expires<=this.now())fail(401,'Administrator authentication required');}
 adminLogout(token){this.db.prepare('DELETE FROM admin_tokens WHERE hash=?').run(hashToken(token||''));}
 upsertClient(input){if(!id(input.id))fail(400,'Invalid client');const data=this.readData();const previous=data.clients.find(c=>c.id===input.id);const client={id:input.id,name:input.name||previous?.name||input.id,status:input.status||previous?.status||'suspended',subscription:input.subscription||previous?.subscription||{plan:'',end:'1970-01-01'},modules:input.modules||previous?.modules||{},profileIds:input.profileIds||previous?.profileIds||[]};data.clients=data.clients.filter(c=>c.id!==client.id);data.clients.push(client);this.saveData(data);this.revokeClient(client.id);return client;}
 upsertModule(input){const data=this.readData();const old=data.modules.find(m=>m.id===input.id);if(!id(input.id))fail(400,'Invalid module');const m={id:input.id,name:input.name||old?.name||input.id,icon:input.icon||old?.icon||'',category:input.category||old?.category||'web',enabled:input.enabled===true,profiles:old?.profiles||[]};data.modules=data.modules.filter(x=>x.id!==m.id);data.modules.push(m);this.saveData(data);return m;}
 upsertProfile(moduleId,input){if(!id(moduleId)||!id(input.id))fail(400,'Invalid profile');const data=this.readData();const m=data.modules.find(x=>x.id===moduleId);if(!m)fail(404,'Module not found');const old=m.profiles.find(p=>p.id===input.id);if(old&&old.url!==cleanUrl(input.url).href)fail(409,'Changing a profile URL requires a new profile and session review');const p={id:input.id,name:input.name,url:cleanUrl(input.url).href,credentialOk:input.credentialOk===true,allowedCookieDomains:input.allowedCookieDomains||[]};m.profiles=m.profiles.filter(x=>x.id!==p.id);m.profiles.push(p);this.saveData(data);return p;}
 enroll(clientId,deviceId,publicKey){if(!id(clientId)||!id(deviceId)||typeof publicKey!=='string'||publicKey.length>2048)fail(400,'Invalid device');const old=this.db.prepare('SELECT * FROM devices WHERE id=?').get(deviceId);if(old){if(old.client_id!==clientId||old.public_key!==publicKey)fail(409,'Device identity already registered');return {deviceId,status:old.status};}this.db.prepare('INSERT INTO devices VALUES(?,?,?,?,?)').run(deviceId,clientId,publicKey,'pending',this.now());this.audit('device-enrolled',clientId,{deviceId});return {deviceId,status:'pending'};}
 device(deviceId){return this.db.prepare('SELECT * FROM devices WHERE id=?').get(deviceId);}
 setDeviceStatus(clientId,deviceId,status){if(!['active','revoked'].includes(status))fail(400,'Invalid device status');const r=this.db.prepare('UPDATE devices SET status=? WHERE id=? AND client_id=?').run(status,deviceId,clientId);if(!r.changes)fail(404,'Device not found');this.revokeDevice(deviceId);this.audit('device-'+status,clientId,{deviceId});}
 listDevices(){return this.db.prepare('SELECT id,client_id,status,created FROM devices').all();}
 revokeDevice(deviceId){const rows=this.db.prepare('SELECT hash,data FROM sessions').all();for(const r of rows)if(parse(r.data).deviceId===deviceId)this.db.prepare('DELETE FROM sessions WHERE hash=?').run(r.hash);}
 revokeClient(clientId){const rows=this.db.prepare('SELECT hash,data FROM sessions').all();for(const r of rows)if(parse(r.data).clientId===clientId)this.db.prepare('DELETE FROM sessions WHERE hash=?').run(r.hash);}
 useNonce(deviceId,nonce,expires){if(!id(deviceId)||!id(nonce)||!Number.isFinite(expires))fail(401,'Invalid device proof');this.db.prepare('DELETE FROM nonces WHERE expires<?').run(this.now());try{this.db.prepare('INSERT INTO nonces VALUES(?,?,?)').run(deviceId,nonce,expires);}catch{fail(401,'Replayed device proof');}}
 encrypt(value,aad){const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',this.key,iv);cipher.setAAD(Buffer.from(aad));const body=Buffer.concat([cipher.update(json(value),'utf8'),cipher.final()]);return json({iv:iv.toString('base64url'),tag:cipher.getAuthTag().toString('base64url'),body:body.toString('base64url')});}
 decrypt(value,aad){const v=parse(value);const decipher=createDecipheriv('aes-256-gcm',this.key,Buffer.from(v.iv,'base64url'));decipher.setAAD(Buffer.from(aad));decipher.setAuthTag(Buffer.from(v.tag,'base64url'));return parse(Buffer.concat([decipher.update(Buffer.from(v.body,'base64url')),decipher.final()]).toString());}
 writeBundle({clientId,moduleId,profileId,url,expiresAt,cookies,attestation}){if(!id(clientId)||!id(moduleId)||!id(profileId)||!date(expiresAt)||Date.parse(expiresAt)<=this.now())fail(400,'Invalid bundle');if(typeof attestation!=='string'||attestation.trim().length<12)fail(400,'Explicit administrator attestation required');const data=this.readData(),client=data.clients.find(c=>c.id===clientId),m=data.modules.find(x=>x.id===moduleId),p=m?.profiles.find(x=>x.id===profileId);if(!client||!m||!p||client.modules?.[moduleId]!==true||!client.profileIds.includes(profileId)||!p.credentialOk||cleanUrl(url).origin!==cleanUrl(p.url).origin)fail(403,'Profile is not explicitly approved');const valid=validateCookies(cookies,p.url,this.now(),p.allowedCookieDomains);const earliest=Math.min(Date.parse(expiresAt),...valid.filter(c=>c.expirationDate!==undefined).map(c=>c.expirationDate*1000));expiresAt=new Date(earliest).toISOString();const version=randomUUID();const aad=json([clientId,moduleId,profileId,version,expiresAt]);const encrypted=this.encrypt({cookies:valid,attestation,source:'admin-verified'},aad);this.db.prepare('INSERT INTO vault VALUES(?,?,?,?,?,?) ON CONFLICT(client_id,module_id,profile_id) DO UPDATE SET version=excluded.version,expires=excluded.expires,ciphertext=excluded.ciphertext').run(clientId,moduleId,profileId,version,expiresAt,encrypted);this.audit('bundle-approved',clientId,{moduleId,profileId,version,count:valid.length});return {version,expiresAt,count:valid.length};}
 readBundle({clientId,moduleId,profileId}){const r=this.db.prepare('SELECT * FROM vault WHERE client_id=? AND module_id=? AND profile_id=?').get(clientId,moduleId,profileId);if(!r)return null;const v=this.decrypt(r.ciphertext,json([clientId,moduleId,profileId,r.version,r.expires]));const p=this.readData().modules.find(m=>m.id===moduleId)?.profiles.find(p=>p.id===profileId);if(!p)return null;return {clientId,moduleId,profileId,url:p.url,approved:true,source:v.source,expiresAt:r.expires,version:r.version,cookies:v.cookies};}
 bundleMetadata({clientId,moduleId,profileId}){const r=this.db.prepare('SELECT version,expires FROM vault WHERE client_id=? AND module_id=? AND profile_id=?').get(clientId,moduleId,profileId);return r&&Date.parse(r.expires)>this.now()?{version:r.version,expiresAt:r.expires}:null;}
 suspendClient(clientId){const data=this.readData(),client=data.clients.find(c=>c.id===clientId);if(!client)fail(404,'Client not found');client.status='suspended';this.saveData(data);this.revokeClient(clientId);this.audit('client-suspended',clientId);}
 revokeBundle(clientId,moduleId,profileId){this.db.prepare('DELETE FROM vault WHERE client_id=? AND module_id=? AND profile_id=?').run(clientId,moduleId,profileId);this.revokeClient(clientId);this.audit('bundle-revoked',clientId,{moduleId,profileId});}
 audit(action,subject,details={}){this.db.prepare('INSERT INTO audit VALUES(?,?,?,?,?)').run(randomUUID(),new Date(this.now()).toISOString(),action,subject,json(details));}
 auditEntries(){return this.db.prepare('SELECT at,action,subject,details FROM audit ORDER BY at DESC LIMIT 200').all().map(r=>({...r,details:parse(r.details)}));}
}
