import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import os from 'node:os';import path from 'node:path';
import {randomBytes} from 'node:crypto';
import {DurableBridgeStore} from './durable-store.mjs';
import {createBridgeGateway} from './gateway.mjs';
import {newDeviceIdentity,signedHeaders} from './device-proof.mjs';
const cookie={name:'session',value:'ONLY-FICTIONAL',domain:'example.test',secure:true,httpOnly:true,expirationDate:Date.now()/1000+3600};
function fixture(){const dir=mkdtempSync(path.join(os.tmpdir(),'uf-bridge-')),key=randomBytes(32),filename=path.join(dir,'db.sqlite');const store=new DurableBridgeStore({filename,key});const gateway=createBridgeGateway({store});return {store,gateway,filename,key,close:()=>{store.close();rmSync(dir,{recursive:true,force:true});}};}
async function request(url,method='GET',body,headers={}){const payload=body===undefined?'':JSON.stringify(body);const r=await fetch(url,{method,headers:{...(body===undefined?{}:{'Content-Type':'application/json'}),...headers},body:body===undefined?undefined:payload});return {status:r.status,headers:r.headers,data:await r.json()};}
function setup(s){s.bootstrapAdmin('owner','A-long-private-test-password-1');s.upsertModule({id:'m',name:'Example',enabled:true});s.upsertProfile('m',{id:'p',name:'Example',url:'https://example.test/a',credentialOk:true});s.upsertClient({id:'a',name:'Alice',status:'active',subscription:{plan:'test',end:'2026-12-31'},modules:{m:true},profileIds:['p']});s.upsertClient({id:'b',name:'Bob',status:'active',subscription:{plan:'test',end:'2026-12-31'},modules:{m:true},profileIds:[]});s.setCredential('a','alice','A-long-private-test-password-2');s.setCredential('b','bob','A-long-private-test-password-3');}
test('passwords are hashed, vault encrypted and restart preserves data',()=>{const f=fixture();try{setup(f.store);const result=f.store.writeBundle({clientId:'a',moduleId:'m',profileId:'p',url:'https://example.test/a',expiresAt:'2026-12-01',cookies:[cookie],attestation:'Test account explicitly approved'});assert.equal(result.count,1);assert.ok(!JSON.stringify(f.store.db.prepare('SELECT ciphertext FROM vault').all()).includes('ONLY-FICTIONAL'));assert.ok(!JSON.stringify(f.store.db.prepare('SELECT * FROM credentials').all()).includes('A-long-private-test-password'));assert.ok(f.store.authenticate({identifier:'alice',password:'A-long-private-test-password-2',deviceId:'x'}));assert.equal(f.store.authenticate({identifier:'alice',password:'wrong',deviceId:'x'}),null);f.store.db.close();const reopened=new DurableBridgeStore({filename:f.filename,key:f.key});assert.equal(reopened.readBundle({clientId:'a',moduleId:'m',profileId:'p'}).cookies[0].value,'ONLY-FICTIONAL');assert.equal(reopened.readBundle({clientId:'b',moduleId:'m',profileId:'p'}),null);reopened.close();const wrong=new DurableBridgeStore({filename:f.filename,key:randomBytes(32)});assert.throws(()=>wrong.readBundle({clientId:'a',moduleId:'m',profileId:'p'}));wrong.close();}finally{rmSync(path.dirname(f.filename),{recursive:true,force:true});}});
test('signed native flow requires approval, filters catalog and revokes access',async()=>{const f=fixture(),server=await f.gateway.listen(),base='http://127.0.0.1:'+server.address().port,identity=newDeviceIdentity();try{setup(f.store);const body={identifier:'alice',password:'A-long-private-test-password-2',deviceId:identity.deviceId,publicKey:identity.publicKey};const payload=JSON.stringify(body);const headers={...signedHeaders(identity,'POST','/enroll',payload),'Content-Type':'application/json'};assert.equal((await fetch(base+'/api/bridge/v1/enroll',{method:'POST',headers,body:payload})).status,200);assert.equal((await fetch(base+'/api/bridge/v1/enroll',{method:'POST',headers,body:payload})).status,401);f.store.setDeviceStatus('a',identity.deviceId,'active');const loginBody={identifier:'alice',password:'A-long-private-test-password-2',deviceId:identity.deviceId};const raw=JSON.stringify(loginBody);const login=await request(base+'/api/bridge/v1/login','POST',loginBody,signedHeaders(identity,'POST','/login',raw));assert.equal(login.status,200);const auth={Authorization:'Bearer '+login.data.token};const cat=await request(base+'/api/bridge/v1/catalog','GET',undefined,{...auth,...signedHeaders(identity,'GET','/catalog','')});assert.equal(cat.data.modules[0].profiles[0].sessionAvailable,false);assert.equal(JSON.stringify(cat.data).includes('ONLY-FICTIONAL'),false);f.store.writeBundle({clientId:'a',moduleId:'m',profileId:'p',url:'https://example.test/a',expiresAt:'2026-12-01',cookies:[cookie],attestation:'Test account explicitly approved'});const sessionBody={moduleId:'m',profileId:'p'},sessionRaw=JSON.stringify(sessionBody);const bundle=await request(base+'/api/bridge/v1/session','POST',sessionBody,{...auth,...signedHeaders(identity,'POST','/session',sessionRaw)});assert.equal(bundle.data.cookies[0].value,'ONLY-FICTIONAL');f.store.revokeBundle('a','m','p');const revoked=await request(base+'/api/bridge/v1/heartbeat','POST',{}, {...auth,...signedHeaders(identity,'POST','/heartbeat','{}')});assert.equal(revoked.status,401);}finally{await new Promise(r=>server.close(r));f.close();}});
test('unassigned clients and unauthenticated admin routes are denied',async()=>{const f=fixture(),server=await f.gateway.listen(),base='http://127.0.0.1:'+server.address().port;try{setup(f.store);assert.equal((await request(base+'/api/bridge/v1/admin/state')).status,401);assert.equal((await request(base+'/api/data')).status,404);const login=await request(base+'/api/bridge/v1/admin/login','POST',{username:'owner',password:'A-long-private-test-password-1'});assert.equal(login.status,200);const auth={Authorization:'Bearer '+login.data.token};const body={clientId:'b',moduleId:'m',profileId:'p',url:'https://example.test/a',expiresAt:'2026-12-01',cookies:[cookie],attestation:'Test account explicitly approved'};assert.equal((await request(base+'/api/bridge/v1/admin/bundles','POST',body,auth)).status,403);assert.equal((await request(base+'/api/bridge/v1/admin/state','GET',undefined,auth)).status,200);}finally{await new Promise(r=>server.close(r));f.close();}});
